apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ECR_REGISTRY/k8s-project
  newName: ECR_REGISTRY/k8s-project-backend
  newTag: c6122d4301b52995efa3a8c8a33926884796d9b3
