apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ECR_REGISTRY/k8s-project
  newName: ECR_REGISTRY/k8s-project-backend
  newTag: aa6caccdd4026f933c382f9877540982e7defdaf
